### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by solitonmedic** [blazekjan/docker-selfhosted-apps#1]
Hello, I've been following along and was able to get the containers running, however I run into a blank page on the domain Nextcloud was supposed to be hosted on.

What seems to be happening?

Nextcloud Compose.yaml

```
services:
  nextcloud-db:
    image: postgres:13
    container_name: nextcloud-db
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - ./nextcloud_db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: nextcloud # fill the database user eg. nextcloud
      POSTGRES_PASSWORD: <password> # fill the database password

  nextcloud-cache:
    image: redis:7.0.4-alpine
    container_name: nextcloud-cache
    restart: unless-stopped
    networks:
      - caddy
    command: redis-server --requirepass <password> # change the password to whatever you want 

  nextcloud-app:
    image: nextcloud:stable-fpm-alpine
    container_name: nextcloud-app
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - ./nextcloud_data/:/var/www/html  
    depends_on:
      - nextcloud-db
      - nextcloud-cache
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud # fill the database user eg. nextcloud
      POSTGRES_PASSWORD: <password> # fill the database password
      POSTGRES_HOST: nextcloud-db
      NEXTCLOUD_ADMIN_USER: adjule # fill the user eg. admin
      NEXTCLOUD_ADMIN_PASSWORD: <password> # fill the admin password
      NEXTCLOUD_TRUSTED_DOMAINS: <domain> # fill the domain you are accessing from eg. nextcloud.mydomain.com
      REDIS_HOST: nextcloud-cache
      REDIS_HOST_PASSWORD: <password> # fill the redis password
    labels:
      caddy: "<domain>" # fill your domain here eg. nextcloud.mydomain.com
      caddy.tls: "adjule" # fill your email here
      caddy.file_server: ""
      caddy.root: "* /nextcloud/var/www/html"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: "/var/www/html"
      caddy.php_fastcgi.env: "front_controller_active true"
      caddy.encode: gzip
      caddy.header: /*
      caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
      caddy.redir_0: "/.well-known/carddav /remote.php/dav"
      caddy.redir_1: "/.well-known/caldav /remote.php/dav"
      caddy.@forbidden.path: "/.htaccess /data/* /config/* /db_structure /.xml /README /3rdparty/* /lib/* /templates/* /occ /console.php"
      caddy.respond: "@forbidden 403"

  nextcloud-cron:
    image: nextcloud:stable-fpm-alpine
    container_name: nextcloud-cron
    restart: always
    volumes:
      - ./nextcloud_data:/var/www/html
    networks:
      - caddy
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db

networks:
  caddy:
    external: true
```

Caddy Compose.yaml

```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-docker-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
      # Nextcloud
      - $DOCKERDIR/nextcloud/nextcloud_data/:/nextcloud/var/www/html
networks:
  caddy:
    external: true
volumes:
  caddy_data:
    external: true

```

caddy .env file

`DOCKERDIR=/home/user/docker/`
